name: "Pull Request Build - development"

on: pull_request
  branches:
    - development

jobs:
  build_java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK 1.8
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk8'
      - name: Build latest Quarkus master
        run:
          - git clone git@github.com:quarkusio/quarkus.git
          - cd quarkus
          - mvn -B clean install -DskipTests -DskipITs
      - name: Build with Maven
        run: mvn -B clean install
